version: 0.2

env:
  variables:
    NPROC: 60
    BUILD_DIR: build_output
#    DISTCC_HOSTS: --randomize distcc.default.svc.cluster.local/84
#    DISTCC_FALLBACK: 0
#    CCACHE_PREFIX: distcc
    CCACHE_DIR: /var/cache/ccache

phases:
  install:
    commands:
      - echo "install phase"
  pre_build:
    commands:
      - echo "pre_build phase"
      - source /opt/rh/devtoolset-8/enable
      - source /opt/rh/rh-python36/enable
      - source /opt/rh/rh-ruby26/enable
  build:
    commands:
      - echo "build phase"
      - find ${CODEBUILD_SRC_DIR} -type f | wc -l
      - mkdir -p /root/src
      - cd /root/src/
      - rsync -aq ${CODEBUILD_SRC_DIR}/. .
      - cmake -S . -B ${BUILD_DIR} -D USE_CCACHE=1 -G Ninja && ninja -C ${BUILD_DIR} -j ${NPROC}
      - rsync -aq . ${CODEBUILD_SRC_DIR}/
      - find ${CODEBUILD_SRC_DIR} -type f| wc -l
  post_build:
    commands:
      - echo "post_build phase"
artifacts:
  files:
    - '**/*'