version: 0.2

env:
  variables:
    NPROC: 60
    BUILD_DIR: build_output

phases:
  install:
    commands:
      - echo "install phase"
  pre_build:
    commands:
      - echo "pre_build phase"
      - source /opt/rh/devtoolset-8/enable
      - source /opt/rh/rh-python36/enable
      - source /opt/rh/rh-ruby26/enable
  build:
    commands:
      - echo "build phase"
      - cd ${BUILD_DIR}
      - cpack -G RPM
  post_build:
    commands:
      - echo "post_build phase"
artifacts:
  files:
    - '**/*'
